[build]
  framework="#custom"
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  included_files = [".next/server/**", ".next/*.json", ".next/BUILD_ID"]

[dev]
  framework="#static"

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[plugins]]
package = "./plugin"